name: Pr10_git_Bez
on: push

jobs:
  Job1:
      runs-on: windows-latest # среда выполнения
      steps:
          - name: Checkout
            uses: actions/checkout@v4 #это версия конкретно выбранного actions
          
          - name: Step2
            uses: actions/setup-dotnet@v3 #делает команду dotnet доступной.
            with:
              dotnet-version: '8.x' #версия .net

          - name: Run project
            run: dotnet run --project ./Pr10_bez/Pr10_bez.csproj #Запуск проекта
